/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as MisTicketsRouteImport } from './routes/mis-tickets'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PqrRouteImport } from './routes/pqr'
import { Route as RecomendadorRouteImport } from './routes/recomendador'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as TestVelocidadRouteImport } from './routes/test-velocidad'
import { Route as VideoSoporteRouteImport } from './routes/video-soporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MisTicketsRoute = MisTicketsRouteImport.update({
  id: '/mis-tickets',
  path: '/mis-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PqrRoute = PqrRouteImport.update({
  id: '/pqr',
  path: '/pqr',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendadorRoute = RecomendadorRouteImport.update({
  id: '/recomendador',
  path: '/recomendador',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TestVelocidadRoute = TestVelocidadRouteImport.update({
  id: '/test-velocidad',
  path: '/test-velocidad',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSoporteRoute = VideoSoporteRouteImport.update({
  id: '/video-soporte',
  path: '/video-soporte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cobertura': typeof CoberturaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresa': typeof EmpresaRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/pagar': typeof PagarRoute
  '/planes': typeof PlanesRoute
  '/pqr': typeof PqrRoute
  '/recomendador': typeof RecomendadorRoute
  '/soporte': typeof SoporteRoute
  '/test-velocidad': typeof TestVelocidadRoute
  '/video-soporte': typeof VideoSoporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cobertura': typeof CoberturaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresa': typeof EmpresaRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/pagar': typeof PagarRoute
  '/planes': typeof PlanesRoute
  '/pqr': typeof PqrRoute
  '/recomendador': typeof RecomendadorRoute
  '/soporte': typeof SoporteRoute
  '/test-velocidad': typeof TestVelocidadRoute
  '/video-soporte': typeof VideoSoporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cobertura': typeof CoberturaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresa': typeof EmpresaRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/pagar': typeof PagarRoute
  '/planes': typeof PlanesRoute
  '/pqr': typeof PqrRoute
  '/recomendador': typeof RecomendadorRoute
  '/soporte': typeof SoporteRoute
  '/test-velocidad': typeof TestVelocidadRoute
  '/video-soporte': typeof VideoSoporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/cobertura'
    | '/diagnostico'
    | '/empresa'
    | '/mis-tickets'
    | '/pagar'
    | '/planes'
    | '/pqr'
    | '/recomendador'
    | '/soporte'
    | '/test-velocidad'
    | '/video-soporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/cobertura'
    | '/diagnostico'
    | '/empresa'
    | '/mis-tickets'
    | '/pagar'
    | '/planes'
    | '/pqr'
    | '/recomendador'
    | '/soporte'
    | '/test-velocidad'
    | '/video-soporte'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/cobertura'
    | '/diagnostico'
    | '/empresa'
    | '/mis-tickets'
    | '/pagar'
    | '/planes'
    | '/pqr'
    | '/recomendador'
    | '/soporte'
    | '/test-velocidad'
    | '/video-soporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  CoberturaRoute: typeof CoberturaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EmpresaRoute: typeof EmpresaRoute
  MisTicketsRoute: typeof MisTicketsRoute
  PagarRoute: typeof PagarRoute
  PlanesRoute: typeof PlanesRoute
  PqrRoute: typeof PqrRoute
  RecomendadorRoute: typeof RecomendadorRoute
  SoporteRoute: typeof SoporteRoute
  TestVelocidadRoute: typeof TestVelocidadRoute
  VideoSoporteRoute: typeof VideoSoporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-tickets': {
      id: '/mis-tickets'
      path: '/mis-tickets'
      fullPath: '/mis-tickets'
      preLoaderRoute: typeof MisTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pqr': {
      id: '/pqr'
      path: '/pqr'
      fullPath: '/pqr'
      preLoaderRoute: typeof PqrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendador': {
      id: '/recomendador'
      path: '/recomendador'
      fullPath: '/recomendador'
      preLoaderRoute: typeof RecomendadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-velocidad': {
      id: '/test-velocidad'
      path: '/test-velocidad'
      fullPath: '/test-velocidad'
      preLoaderRoute: typeof TestVelocidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-soporte': {
      id: '/video-soporte'
      path: '/video-soporte'
      fullPath: '/video-soporte'
      preLoaderRoute: typeof VideoSoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  CoberturaRoute: CoberturaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EmpresaRoute: EmpresaRoute,
  MisTicketsRoute: MisTicketsRoute,
  PagarRoute: PagarRoute,
  PlanesRoute: PlanesRoute,
  PqrRoute: PqrRoute,
  RecomendadorRoute: RecomendadorRoute,
  SoporteRoute: SoporteRoute,
  TestVelocidadRoute: TestVelocidadRoute,
  VideoSoporteRoute: VideoSoporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
